In [1]:
from Decision_tree import DecisionTreeClassifier
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("diabetes.csv")
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data['Outcome'] = le.fit_transform(data['Outcome'])
X = data.iloc[:, :-1].values
Y = data.iloc[:, -1].values.reshape(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=1234)

In [3]:
#Bootstraping
n_records = X_train.shape[0]
indexs = np.random.choice(n_records, n_records, replace=True) # randomly drawing samples from the records with replacement method
print(X_train[indexs], y_train[indexs])

[[4.00e+00 1.09e+02 6.40e+01 ... 3.48e+01 9.05e-01 2.60e+01]
 [0.00e+00 1.19e+02 6.40e+01 ... 3.49e+01 7.25e-01 2.30e+01]
 [8.00e+00 1.20e+02 7.80e+01 ... 2.50e+01 4.09e-01 6.40e+01]
 ...
 [2.00e+00 9.90e+01 6.00e+01 ... 3.66e+01 4.53e-01 2.10e+01]
 [8.00e+00 1.09e+02 7.60e+01 ... 2.79e+01 6.40e-01 3.10e+01]
 [4.00e+00 1.10e+02 7.60e+01 ... 2.84e+01 1.18e-01 2.70e+01]] [[1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0

In [4]:
#fitting
n_estimators=10
trees = []
for i in range(n_estimators):
    dtree = DecisionTreeClassifier()
    X_sample, y_sample = X_train[indexs], y_train[indexs]
    dtree.fit(X_sample, y_sample)# fitting samples to the decision tree
    trees.append(dtree)#load tree to a list

In [5]:
trees

#### Prediction

In [6]:
predictions = np.swapaxes(np.array([dtree.predict(X_test) for dtree in trees]),0,1) # predict the test records for all the trees, swapaxes function transposes the array

In [9]:
# function to find out most frequest values in an array 
def mode_label(x):
    vals,counts = np.unique(x, return_counts=True)
    index = np.argmax(counts)
    return vals[index]

In [10]:
predictions = np.array([mode_label(i) for i in predictions]) # to convert prediction matrix to an array by majority voting method

In [13]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.75      0.86      0.80        99
           1       0.66      0.49      0.56        55

    accuracy                           0.73       154
   macro avg       0.71      0.67      0.68       154
weighted avg       0.72      0.73      0.72       154

